name: Cypress automation for ShopEase

on:
  push:
    paths:
      - 'Automation/**'
    branches: [ Automation ]
  pull_request:
    branches: [ Automation]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Automation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run cy:run

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: |
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore
